#include "builder.h"
#include "counters.h"
#include "simulator_session.h"
#include "backend_reporting.h"
#include "session_mode.h"
#include "cycle_overlap.h"
#include "scheduler_observer.h"
#include "l2_event_audit.h"
#include "../source_root.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sys/resource.h>
namespace native_sequence {
void keys(const J& j,std::initializer_list<const char*> fields){p::need(j.is_object()&&j.size()==fields.size(),"unexpected or missing sequence field; per-kernel memory/map/reset override forbidden");for(auto key:fields)p::need(j.contains(key),"required sequence field missing");}
std::string read_bounded(const std::string& name,U cap){namespace fs=std::filesystem;p::need(fs::is_regular_file(name)&&!fs::is_symlink(name)&&fs::file_size(name)<=cap,"bounded regular non-symlink input required");std::ifstream f(name,std::ios::binary);p::need(bool(f),"input open");std::string text;std::array<char,8192> b{};while(f){f.read(b.data(),b.size());text.append(b.data(),f.gcount());p::need(text.size()<=cap,"file grew beyond bound");}return text;}
std::string check_pin(const J& pin){keys(pin,{"path","bytes","sha256"});const U n=p::natural(pin.at("bytes"),64U<<20);auto s=read_bounded(tilegen_source::resolve(pin.at("path").get<std::string>()),64U<<20);p::need(s.size()==n&&tiny_sha::sha256(s)==pin.at("sha256").get<std::string>(),"source input pin changed");return s;}
J process_identity(const J& program){const auto& b=program.at("source").at("native_binding");const auto& key=b.at("source_launch_key");const auto pid=p::natural(b.at("source_process_id")),ticks=p::natural(b.at("source_start_ticks"));p::need(pid&&ticks&&p::natural(key.at("pid"))==pid&&p::natural(key.at("start_ticks"))==ticks,"process PID/start_ticks binding");const auto spec=program.at("experiment_spec_sha256").get<std::string>();p::need(spec.size()==64,"experiment spec SHA required");p::need(program.at("source").at("begin").at("stream_u64")==b.at("stream_u64"),"BEGIN/native stream mismatch");return {{"pid",pid},{"start_ticks",ticks},{"experiment_spec_sha256",spec},{"context_id",b.at("context_id")},{"context_handle_u64",b.at("context_handle_u64")},{"stream_u64",b.at("stream_u64")}};}
struct SourceBundle {const J input;p::Program program;native_register::Program registers;const native_range_plan::Plan range_plan;U executed;int resident;J identity,budget;g::CtaGraphStore::Limits limits;
 SourceBundle(J value,bool fixture):input(std::move(value)),program(input.at("program")),registers(input.at("register_program"),program,fixture),range_plan(program){const auto& j=input;const bool eager=false;keys(j,{"program","register_program","program_file","register_file","prefix_ctas"});const auto& m=j.at("program");const auto& r=j.at("register_program");const auto& begin=m.at("source").at("begin");p::need(r.at("source_begin")==begin,"exact same-process compute/memory BEGIN");identity=process_identity(m);auto prefix=p::natural(j.at("prefix_ctas"),program.ctas);p::need(prefix==0||prefix<program.ctas,"prefix must be strict partial grid");executed=prefix?prefix:program.ctas;
  const auto& b=m.at("source").at("native_binding");p::need(b.at("epoch_id")==begin.at("epoch_id")&&b.at("epoch_launch_ordinal")==begin.at("epoch_launch_ordinal")&&b.at("sampler_source_launch_key")==begin.at("source_launch_key"),"native launch-key binding");
  if(fixture){p::need(r.at("native_resources").is_null(),"synthetic fixture cannot pretend native occupancy");resident=2;}else{native_family::native_binding(m,r);const auto& q=m.at("qualification");const auto& a=q.at("admission");p::need(a.at("ready_for_modeled_CTA_expansion")==true&&a.at("strict_projection_compatible")==true&&a.at("estimated_static_memory_sites")==0&&native_family::model_memory_holdout_or_exact(m)&&a.at("cross_layer_expansion_qualified")==false,"strict independent native memory qualification required");p::need(q.at("independent_compact_decoder_vs_source_and_HBServe")=="PASS_SELECTED_CTAS_AND_NATIVE_GRID_EXTREMA","native compact decoder qualification");p::need(a.at("source_launch_key")==begin.at("source_launch_key")&&a.at("code_sha256")==begin.at("code_sha256"),"memory admission source/code binding");
   p::need(begin.at("code_sha256")==native_family::begin_descriptor(begin).at("code_sha256")&&begin.at("program_enabled")==true,"sealed native dynamic program required");const auto& resources=begin.at("native_resources");p::need(resources==r.at("native_resources"),"compute/memory native resources mismatch");p::need(resources.at("schema")=="SG_NATIVE_RESOURCES_V1"&&resources.at("attributes_queried_before_instrumentation")==true&&resources.at("occupancy_queried_before_instrumentation")==true,"preinstrument native resources required");p::need(resources.at("attribute_query_results")==J::array({0,0,0,0,0})&&resources.at("occupancy_query_result")==0&&resources.at("threads_per_cta")==native_family::expected_threads(begin),"native resource query success");p::need(p::natural(resources.at("static_shared_bytes"))+p::natural(resources.at("dynamic_shared_bytes"))==p::natural(r.at("shared_allocation_bytes")),"shared allocation binding");resident=int(p::natural(resources.at("max_active_blocks_per_sm"),32));p::need(resident>0,"positive native occupancy cap");p::need(r.at("source_pins").size()>=2,"native register producer evidence required");}
  const auto& plan=range_plan;U ranges=0,original=0,edges=0,subops=0;for(const auto& n:registers.nodes){edges+=n.completion.size()+n.issue.size();if(n.kind=="global"){U count=program.bodies[0].records[n.memory].lanes.size();original+=count;ranges+=plan.records[n.memory].size();if(count)++subops;}else if(n.kind=="shared"){ranges+=n.lanes.size();original+=n.lanes.size();++subops;}}
  limits.max_live_nodes=5000000;const U frontier=std::min(executed,U(2)*48*resident),live_nodes=p::multiply(frontier,registers.nodes.size()),live_ranges=p::multiply(frontier,ranges);p::need(registers.nodes.size()<=limits.max_nodes_per_cta&&ranges<=limits.max_explicit_ranges_per_cta&&live_nodes<=limits.max_live_nodes&&live_ranges<=limits.max_live_explicit_ranges,"conservative resident graph budget exceeded");if(eager)p::need(p::multiply(executed,registers.nodes.size())<=200000,"bounded eager reference exceeded");
  budget={{"conservative_live_ctas",frontier},{"nodes_per_cta",registers.nodes.size()},{"stored_ranges_per_cta",ranges},{"original_lane_ranges_per_cta",original},{"dependency_edges_per_cta",edges},{"explicit_subops_per_cta",subops},{"conservative_live_nodes",live_nodes},{"conservative_live_ranges",live_ranges},{"limits",{{"live_nodes",limits.max_live_nodes},{"live_ranges",limits.max_live_explicit_ranges}}},{"basis","effective global spans plus unchanged shared lanes; min(executedCTAs,2*48SM*residency); explicit5m host-node guard, all other limits unchanged"}};
 }
};

// A stable owning bundle precedes every reference to it. Neither the catalog nor
// any call mutates source BEGIN, source address rules, typed nodes or topology.
struct Prepared {
 const SourceBundle& bundle;const J& input;const p::Program& program;const native_register::Program& registers;
 U executed;int resident;J identity,budget;g::CtaGraphStore::Limits limits;std::string catalog_id;
 Prepared(const SourceBundle& source,const J& call,bool eager):bundle(source),input(source.input),program(source.program),registers(source.registers),resident(source.resident),identity(source.identity),budget(source.budget),limits(source.limits),catalog_id(call.at("catalog_id")){
  keys(call,{"catalog_id","prefix_ctas"});auto prefix=p::natural(call.at("prefix_ctas"),program.ctas);p::need(prefix==0||prefix<program.ctas,"prefix must be strict partial grid");executed=prefix?prefix:program.ctas;
  U frontier=std::min(executed,U(2)*48*resident),live=p::multiply(frontier,registers.nodes.size()),ranges=p::multiply(frontier,p::natural(budget.at("stored_ranges_per_cta")));
  p::need(live<=limits.max_live_nodes&&ranges<=limits.max_live_explicit_ranges,"conservative resident graph budget exceeded");if(eager)p::need(p::multiply(executed,registers.nodes.size())<=200000,"bounded eager reference exceeded");
  budget["conservative_live_ctas"]=frontier;budget["conservative_live_nodes"]=live;budget["conservative_live_ranges"]=ranges;
 }
};
struct SealRegistry {
 std::map<std::string,J> pins;U verified=0,final_checks=0;std::set<std::string> retained_sources;
 std::string load_source(const J& pin){auto path=pin.at("path").get<std::string>();p::need(retained_sources.insert(path).second,"duplicate source artifact path");auto raw=check_pin(pin);p::need(raw.size()<=32U<<20,"source artifact exceeds inherited wrapper bound");remember(pin);++verified;return raw;}
 void remember(const J& pin){auto path=pin.at("path").get<std::string>();auto it=pins.find(path);p::need(it==pins.end()||it->second==pin,"inconsistent pin for one source path");pins.emplace(path,pin);p::need(pins.size()<=2048,"bounded unique evidence pin count");}
 void evidence(const J& pin){auto path=pin.at("path").get<std::string>();auto it=pins.find(path);if(it!=pins.end()){p::need(it->second==pin,"inconsistent evidence pin");return;}remember(pin);(void)check_pin(pin);++verified;}
 void finish(){for(const auto& [path,pin]:pins){(void)check_pin(pin);++final_checks;}}
};
J strict_parse(const std::string& raw){std::vector<std::set<std::string>> stack;auto cb=[&](int,nlohmann::json::parse_event_t e,J& v){if(e==nlohmann::json::parse_event_t::object_start)stack.emplace_back();if(e==nlohmann::json::parse_event_t::key)p::need(stack.back().insert(v.get<std::string>()).second,"duplicate source JSON key");if(e==nlohmann::json::parse_event_t::object_end)stack.pop_back();return true;};return J::parse(raw,cb);}
struct SourceCatalog {
 SealRegistry seals;std::map<std::string,std::unique_ptr<const SourceBundle>> bundles;std::set<std::pair<std::string,std::string>> artifacts;U bytes=0,records=0,lanes=0,nodes=0,edges=0,edge_bound=0,typed_edges=0,source_parses=0;
 SourceCatalog(const J& list,bool fixture){p::need(list.is_array()&&list.size()>=1&&list.size()<=19,"catalog requires one through nineteen unique sources");
  for(const auto& ref:list){keys(ref,{"catalog_id","program_file","register_file"});auto id=ref.at("catalog_id").get<std::string>();p::need(!id.empty()&&id.size()<=128&&!bundles.count(id),"duplicate/invalid catalog id");
   auto pair=std::make_pair(ref.at("program_file").at("sha256").get<std::string>(),ref.at("register_file").at("sha256").get<std::string>());p::need(artifacts.insert(pair).second,"duplicate source pair must share one catalog entry");
   bytes=p::add(bytes,p::add(p::natural(ref.at("program_file").at("bytes")),p::natural(ref.at("register_file").at("bytes"))));p::need(bytes<=64U<<20,"aggregate encoded source pool exceeds64MiB");
   J m=strict_parse(seals.load_source(ref.at("program_file"))),r=strict_parse(seals.load_source(ref.at("register_file")));source_parses+=2;
   for(const auto& body:m.at("programs"))for(const auto& record:body.at("records")){records=p::add(records,1);lanes=p::add(lanes,record.at("lanes").size());}
   U extra_barrier_edges=0,source_edges=0;for(const auto& warp:r.at("warps"))for(const auto& n:warp.at("nodes")){nodes=p::add(nodes,1);source_edges=p::add(source_edges,p::add(n.at("depends_on").size(),n.at("issue_depends_on").size()));if(n.at("kind")=="barrier")extra_barrier_edges=p::add(extra_barrier_edges,r.at("warps").size()-1);}edges=p::add(edges,source_edges);edge_bound=p::add(edge_bound,p::add(source_edges,extra_barrier_edges));
   p::need(records<=32768&&lanes<=1048576&&nodes<=131072&&edge_bound<=524288,"aggregate typed source census exceeds unchanged pooled source bounds");
   const auto& pins=r.at("source_pins");p::need(pins.is_array()&&pins.size()<=128,"bounded producer evidence pins");for(const auto& pin:pins)seals.evidence(pin);
   if(!fixture&&native_family::is_fused_key(r.at("source_launch_key").get<std::string>()))for(const auto& pin:native_family::fused_model_manifest().at("required_runtime_evidence"))seals.evidence(pin);
   if(!fixture&&native_family::is_norm_key(r.at("source_launch_key").get<std::string>()))for(const auto& pin:native_family::norm_model_manifest().at("required_runtime_evidence"))seals.evidence(pin);
   J entry={{"program",std::move(m)},{"register_program",std::move(r)},{"program_file",ref.at("program_file")},{"register_file",ref.at("register_file")},{"prefix_ctas",0}};native_family::sealed_artifact(entry,fixture);auto bundle=std::make_unique<const SourceBundle>(std::move(entry),fixture);typed_edges=p::add(typed_edges,p::natural(bundle->budget.at("dependency_edges_per_cta")));p::need(typed_edges<=edge_bound,"typed edge census exceeds conservative BAR expansion bound");bundles.emplace(id,std::move(bundle));
  }
 }
 const SourceBundle& get(const std::string& id)const{auto it=bundles.find(id);p::need(it!=bundles.end(),"unknown catalog reference");return *it->second;}
 J receipt()const{return {{"schema","IMMUTABLE_SOURCE_POOL_RECEIPT_V1"},{"sources",bundles.size()},{"source_json_parses",source_parses},{"oracle_validations",bundles.size()},{"topology_compilations",bundles.size()},{"range_plan_compilations",bundles.size()},{"encoded_source_bytes",bytes},{"memory_records",records},{"memory_lane_tuples",lanes},{"register_template_nodes",nodes},{"declared_register_dependency_edges",edges},{"typed_register_dependency_edges",typed_edges},{"register_dependency_edge_upper_bound",edge_bound},{"unique_evidence_pins_verified",seals.verified},{"final_unique_pin_rechecks",seals.final_checks},{"source_bytes_are_RSS",false},{"typed_pool_census_is_dynamic_DAG_size",false},{"target_transfer_admission_enabled",false},{"retained_DOM_copies_per_source",1},{"budgets",{{"encoded_bytes",64U<<20},{"memory_records",32768},{"memory_lanes",1048576},{"register_nodes",131072},{"register_edges",524288},{"live_dynamic_nodes",5000000}}}};}
};
J service_map(const std::vector<std::unique_ptr<Prepared>>& prepared){std::vector<std::pair<U,U>> spans;for(const auto& k:prepared)for(const auto& o:k->program.objects){U end=p::add(o.base,o.bytes);p::need(end<=UINT64_MAX-127,"aligned object end overflow");spans.emplace_back(o.base/128*128,(end+127)/128*128);}std::sort(spans.begin(),spans.end());std::vector<std::pair<U,U>> merged;for(auto [lo,hi]:spans){if(!merged.empty()&&lo<=merged.back().second)merged.back().second=std::max(hi,merged.back().second);else merged.emplace_back(lo,hi);}J rows=J::array();U offset=0;for(auto [lo,hi]:merged){rows.push_back({{"source_base",lo},{"bytes",hi-lo},{"service_base",offset}});offset=p::add(offset,hi-lo);}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};}
struct Mapper final:g::L2DramAddressMapper{U map(const g::CacheLineKey& k)const override{p::need(k.matrix_id==1,"unknown process VA root");return k.line_addr;}};
std::string list_digest(const std::vector<std::string>& values){tiny_sha::Sha256 d;for(const auto& value:values){p::need(value.size()==64,"missing retired CTA audit");d.add(value+"\n");}return d.hex();}
J placement_receipt(int count,int warps,int resident){
 J all=J::array(),initial=J::array();for(int sm=0;sm<48;++sm){all.push_back(J::array({0,0,0,0}));initial.push_back(J::array({0,0,0,0}));}
 for(int c=0;c<count;++c)for(int w=0;w<warps;++w){int sp=g::cta_placement::token(c,w,warps,48,4,true)%4;all[c%48][sp]=all[c%48][sp].get<int>()+1;if(c/48<resident)initial[c%48][sp]=initial[c%48][sp].get<int>()+1;}
 return {{"rule","PER_SM_CTA_ORDINAL_WARP_TOKEN_V1"},{"source_warp_count",count*warps},{"scheduler_token_domain",g::cta_placement::domain(count,warps,48,4,true)},{"all_assigned_warps_per_SM_SP",all},{"initial_resident_assigned_warps_per_SM_SP",initial},{"assignment_is_hardware_measurement",false},{"per_SM_CTA_ordinal_is_resident_slot_allocator",false}};
}
J run(const J& in,bool validate,bool eager,bool events){auto start=Clock::now();keys(in,{"schema","scope","synthetic_fixture_only","memory_model","service_address_map","max_kernel_cycles","aggregate_observations","source_catalog","pipeline"});p::need(in.at("schema")=="TILEGEN_POOLED_NATIVE_SEQUENCE_V1","pooled sequence schema required");p::need(in.at("synthetic_fixture_only").is_boolean()&&in.at("aggregate_observations").is_boolean(),"explicit mode flags");bool fixture=in.at("synthetic_fixture_only").get<bool>(),observe=in.at("aggregate_observations").get<bool>();p::need(in.at("memory_model").at("backend")=="hbf_gddr6","one native HBFSIM backend required");const bool stress=in.at("scope")=="SYNTHETIC_POOLED_SEQUENCE_STRESS";p::need((stress&&fixture)||in.at("scope")=="SELECTED_KERNEL_SEQUENCE_DIAGNOSTIC_WITH_OMITTED_LAUNCHES","explicit selected or synthetic stress scope required");const auto& list=in.at("pipeline");p::need(list.is_array()&&list.size()>=1&&list.size()<=(stress?1138:19),"bounded identity-selected or synthetic stress list");SourceCatalog catalog(in.at("source_catalog"),fixture);std::vector<std::unique_ptr<Prepared>> prepared;std::set<std::string> used_catalog;
 for(const auto& k:list){keys(k,{"catalog_id","prefix_ctas"});auto id=k.at("catalog_id").get<std::string>();used_catalog.insert(id);prepared.push_back(std::make_unique<Prepared>(catalog.get(id),k,eager));}p::need(used_catalog.size()==catalog.bundles.size(),"unused catalog entries forbidden");
 U skipped=0,last_launch=0;std::size_t last_descriptor=0;std::set<std::string> seen;J gaps=J::array();
 for(std::size_t i=0;i<prepared.size();++i){p::need(prepared[0]->identity==prepared[i]->identity,"sequence mixes process/spec/context/stream identities");const auto& m=prepared[i]->input.at("program");const auto key=m.at("source").at("begin").at("source_launch_key").get<std::string>();p::need(stress||seen.insert(key).second,"duplicate selected source key");U launch=p::natural(m.at("source").at("native_binding").at("source_launch_key").at("launch_id"));if(i&&!stress){p::need(launch>last_launch,"source launch order must increase");U gap=launch-last_launch-1;skipped=p::add(skipped,gap);gaps.push_back({{"after_source",prepared[i-1]->input.at("program").at("source").at("begin").at("source_launch_key")},{"before_source",key},{"omitted_launches",gap}});}if(!fixture){auto rank=native_family::index_for(key);if(i)p::need(rank>last_descriptor,"sealed descriptor phase/order must increase");last_descriptor=rank;}last_launch=launch;}p::need(in.at("service_address_map")==service_map(prepared),"workflow map must be canonical union of selected source VA carriers");
 const auto max_cycles=g::Cycle(p::natural(in.at("max_kernel_cycles"),2000000000));p::need(max_cycles>0,"positive max cycles");auto cfg=g::make_rtx4000_ada_footprint_reference_config();cfg.silence_mode=true;cfg.workload_type=g::WorkloadType::Llama3Elementwise;Mapper mapper;coupling::Runtime memory(in,cfg,mapper);p::need(bool(memory.backend),"external backend required");
 J result={{"schema","TILEGEN_POOLED_NATIVE_SEQUENCE_RESULT_V1"},{"status",validate?"VALIDATED_NOT_EXECUTED":fixture?"SYNTHETIC_NATIVE_STRUCTURE_SEQUENCE_EXECUTED":"NATIVE_SELECTED_KERNEL_SEQUENCE_DIAGNOSTIC_EXECUTED"},{"scope",in.at("scope")},{"synthetic_fixture_only",fixture},{"full_LLM_state",false},{"complete_SGLang_phase",false},{"full_LLM_time_ns",nullptr},{"full_LLM_bandwidth_GBps",nullptr},{"omitted_launches_executed",false},{"source_launch_id_gap",skipped},{"source_launch_gaps",gaps},{"selected_source_count",prepared.size()},{"admission_cardinality_version","ONE_TO_NINETEEN_EXPLICIT_FUSED_NORM_MODEL_V1"},{"scheduler_warp_identity","PER_SM_CTA_ORDINAL_WARP_TOKEN_V1"},{"source_warp_identity","immutable CTA-local register/memory source warp; not scheduler token"},{"per_node_hash_warp_field","SCHEDULER_WARP_TOKEN"},{"physical_hardware_SP_assignment_recovered",false},{ "event_hash_namespace",prepared.size()==1?"NONE_SINGLE_SOURCE":"KERNEL_INDEX_PREFIX"},{"descriptor_catalog_size",19},{"qualified_silu_source_count",native_family::silu_qualified().size()},{"qualified_a67_source_count",native_family::a67_qualified().size()},{"same_scope_NCU_measurement_available",false},{"hardware_error_percent",nullptr},{"cache_history_scope","initial cold cache plus only selected modeled kernels; omitted native launches would change cache history, so this is not actual later-phase cache state"},{"process_identity",prepared[0]->identity},{"cache_identity_qualification",{{"domain","same process and CUDA context, 128B virtual-address lines"},{"allocator_lifetime_proven",false},{"physical_address_reuse_proven",false},{"VA_reuse_assumed_for_selected_sequence_model",true},{"actual_cross_phase_cache_state_recovered",false}}},{"L1_policy",{{"mode",g::per_sm_l1_mode_name(cfg.per_sm_l1.mode)},{"persistence",g::per_sm_l1_persistence_name(cfg.per_sm_l1.persistence)}}},{"boundary_policy",{{"quiescence_per_kernel",true},{"L2_reset",false},{"backend_reset",false},{"final_dirty_flush",false},{"native_async_store_overlap_modeled",false}}},{"materialization",eager?"bounded_eager_reference":"resident_CTA"},{"event_mode",events},{"aggregate_observations",observe},{"pipeline",J::array()}};
 result["source_catalog"]=J::object();
 for(const auto& k:prepared){if(!result["source_catalog"].contains(k->catalog_id))result["source_catalog"][k->catalog_id]={{"source_launch_key",k->program.identity.at("begin").at("source_launch_key")},{"source_oracle_validation",k->program.oracle_receipt},{"memory_source_qualification",k->program.qualification},{"compute_model_assumptions",k->registers.assumptions},{"register_census",k->registers.census()},{"declared_ctas",k->program.ctas},{"native_resident_cta_capacity",fixture?J(nullptr):J(k->resident)},{"modeled_resident_cta_limit",k->resident},{"program_file",k->input.at("program_file")},{"register_file",k->input.at("register_file")}};
  result["pipeline"].push_back({{"catalog_id",k->catalog_id},{"executed_ctas",k->executed},{"prefix_only",k->executed!=k->program.ctas},{"graph_budget",k->budget},{"warp_placement",placement_receipt(int(k->executed),k->program.warps,k->resident)}});
 }
 for(const auto& k:prepared)if(native_family::is_fused_key(k->program.identity.at("begin").at("source_launch_key").get<std::string>()))result["source_catalog"][k->catalog_id]["explicit_model_scope"]=native_family::fused_model_scope();
 for(const auto& k:prepared)if(native_family::is_norm_key(k->program.identity.at("begin").at("source_launch_key").get<std::string>()))result["source_catalog"][k->catalog_id]["explicit_model_scope"]=native_family::norm_model_scope();
 if(validate){catalog.seals.finish();result["source_pool"]=catalog.receipt();return result;}
 g::ContinuousL2Session session(cfg,memory.backend.get(),memory.mapper.get());tiny_runtime::sp_event_mode=events;const auto initial=session.statistics();g::Cycle previous=0,sum_windows=0,sum_kernel=0,sum_drain=0;U sum_r=0,sum_w=0,prior_r=0,prior_w=0;tiny_sha::Sha256 workflow_digest;double engine_total=0;
 for(std::size_t index=0;index<prepared.size();++index){const auto& k=*prepared[index];session.set_next_kernel_resident_cta_limit(k.resident);Builder builder(k.program,k.registers,*memory.mapper,k.executed,k.bundle.range_plan);builder.fast_hash=true;builder.merge_ranges=true;builder.kernel_index=int(index);g::DAG dag;std::unique_ptr<g::CtaGraphStore> store;
  if(eager){for(U c=0;c<k.executed;++c)for(auto& n:builder.build(int(c)))dag.add_node(n.release());}else{store=std::make_unique<g::CtaGraphStore>(g::CtaGraphStore::Spec{int(k.executed),k.program.warps,48,p::multiply(k.registers.nodes.size(),k.executed),builder.spans,k.resident,true},[&](int c){return builder.build(c);},[&](int c,const std::vector<g::DAGNode*>& ns,g::Cycle cy){builder.retire(c,ns,cy);},k.limits);dag.cta_graph_store=store.get();}
  g::scheduler_observer::reset();g::scheduler_observer::set_enabled(observe);g::cycle_overlap::begin(cfg.num_sms,4,session.cycle(),observe);host_range_audit::L2Events audit;if(prepared.size()>1)audit.digest.add("kernel="+std::to_string(index)+"\n");auto tick=Clock::now();auto r=session.run_kernel(&dag,max_cycles,false,&audit,nullptr,10000000);double engine=std::chrono::duration<double>(Clock::now()-tick).count();engine_total+=engine;J overlap=g::cycle_overlap::finish(r.kernel_end_cycle),scheduler=g::scheduler_observer::snapshot_json();g::scheduler_observer::set_enabled(false);
  if(eager)for(U c=0;c<k.executed;++c){auto span=builder.spans[c];std::vector<g::DAGNode*> ns(dag.nodes.begin()+span.first_node,dag.nodes.begin()+span.first_node+span.node_count);builder.retire(int(c),ns,session.cycle());}
  p::need(builder.built_nodes==builder.retired_nodes&&builder.retired_nodes==p::multiply(k.registers.nodes.size(),k.executed)&&builder.retired_ctas==k.executed,"complete selected grid retirement");p::need(builder.read==p::multiply(k.program.bodies[0].read,k.executed)&&builder.write==p::multiply(k.program.bodies[0].write,k.executed),"requested traffic closure");p::need(session.is_quiescent()&&r.start_cycle==previous&&r.quiescent_end_cycle==session.cycle(),"continuous cycle and quiescence closure");if(index)p::need(stats(r.before)==result["pipeline"][index-1].at("execution").at("after"),"cumulative counters reset between sources");
  auto d=delta(stats(r.after),stats(r.before));U rd=d.at("dram_fill_requests").get<U>()*128,wr=d.at("dram_writeback_requests").get<U>()*128;auto physical=memory.backend->physical_statistics();p::need(physical.read_bytes-prior_r==rd&&physical.write_bytes-prior_w==wr,"per-source native/L2 byte delta");prior_r=physical.read_bytes;prior_w=physical.write_bytes;const auto& a=memory.backend->admission_statistics();p::need(a.accepted==a.completed&&a.reserved_bursts==0&&memory.backend->queue_depth()==0,"per-source finite credits not closed");p::need(r.after.accepted_transactions==r.after.processed_transactions&&r.after.dram_fill_requests==r.after.dram_fill_completions&&r.after.dram_writeback_requests==r.after.dram_writeback_completions,"per-source memory completion closure");
  const std::string digest=list_digest(builder.retired_kernel_semantics);workflow_digest.add(std::to_string(index)+":"+digest+"\n");J e={{"start_cycle",r.start_cycle},{"kernel_end_cycle",r.kernel_end_cycle},{"quiescent_end_cycle",r.quiescent_end_cycle},{"kernel_cycles",r.kernel_end_cycle-r.start_cycle},{"drain_cycles",r.drain_cycles},{"window_cycles",r.quiescent_end_cycle-r.start_cycle},{"before",stats(r.before)},{"after",stats(r.after)},{"counter_delta",d},{"gauges_after",gauges(r.after)},{"DRAM_read_bytes",rd},{"DRAM_write_bytes",wr},{"requested_read_bytes",builder.read},{"requested_write_bytes",builder.write},{"retired_nodes",builder.retired_nodes},{"retired_ctas",builder.retired_ctas},{"kernel_prefixed_per_node_sha256",digest},{"unprefixed_per_node_sha256",list_digest(builder.retired_semantics)},{"ordered_l2_events",audit.receipt()},{"cycle_overlap",overlap},{"scheduler_visits",scheduler},{"finite_credits",{{"accepted_cumulative",a.accepted},{"completed_cumulative",a.completed},{"peak_live_cumulative",a.peak_live},{"reserved_bursts",a.reserved_bursts},{"outer_queue",memory.backend->queue_depth()}}},{"host_engine_seconds",engine}};
  if(store){auto t=store->telemetry();p::need(t.at("live_nodes")==0&&t.at("live_ctas")==0,"resident graph not reclaimed");e["resident_graph"]=t;}result["pipeline"][index]["execution"]=e;sum_windows+=r.quiescent_end_cycle-r.start_cycle;sum_kernel+=r.kernel_end_cycle-r.start_cycle;sum_drain+=r.drain_cycles;sum_r+=rd;sum_w+=wr;previous=r.quiescent_end_cycle;
 }
 p::need(sum_windows==session.cycle()&&sum_kernel+sum_drain==sum_windows,"workflow time closure");auto d=delta(stats(session.statistics()),stats(initial));p::need(d.at("dram_fill_requests").get<U>()*128==sum_r&&d.at("dram_writeback_requests").get<U>()*128==sum_w,"workflow traffic closure");memory.backend->finalize();sg_hbf::require_external_only(session.l2());auto physical=memory.backend->physical_statistics();p::need(physical.read_bytes==sum_r&&physical.write_bytes==sum_w,"final native ledger closure");catalog.seals.finish();
 const auto& clock=in.at("memory_model").at("clock");long double cycle_ns=clock.at("period_ps_numerator").get<long double>()/clock.at("period_ps_denominator").get<long double>()/1000;for(auto& item:result["pipeline"]){auto& e=item["execution"];double ns=double(e.at("window_cycles").get<U>()*cycle_ns);e["time_ns"]=ns;e["DRAM_GBps"]=double(e.at("DRAM_read_bytes").get<U>()+e.at("DRAM_write_bytes").get<U>())/ns;}
 double ns=double(sum_windows*cycle_ns);result["workflow"]={{"window_cycles",sum_windows},{"kernel_cycles_sum",sum_kernel},{"drain_cycles_sum",sum_drain},{"clock",clock},{"time_ns",ns},{"DRAM_read_bytes",sum_r},{"DRAM_write_bytes",sum_w},{"DRAM_GBps",double(sum_r+sum_w)/ns},{"counter_delta",d},{"kernel_prefixed_node_sha256",workflow_digest.hex()},{"end_is_quiescent",session.is_quiescent()}};result["memory_backend"]={{"identity",memory.device_identity},{"physical_statistics",tiny_hbf_reporting::native_statistics(physical)},{"memory_path",tiny_hbf_reporting::path_statistics(*memory.backend)},{"runtime_instances",1},{"continuous_sessions",1},{"finalize_calls",1}};result["host"]={{"engine_seconds",engine_total},{"total_seconds",std::chrono::duration<double>(Clock::now()-start).count()}};result["source_pool"]=catalog.receipt();result["full_trace_saved"]=false;result["retry_host_work"]=g::retry_host::snapshot();return result;
}
}
int main(int argc,char** argv){GTSim::retry_host::prefix_enabled=true;GTSim::retry_host::ready_front_enabled=true;try{bool validate=false,eager=false,events=true;std::string path;for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="--validate-only")validate=true;else if(a=="--eager-reference")eager=true;else if(a=="--event-off")events=false;else if(a=="--retry-prefix-off")GTSim::retry_host::prefix_enabled=false;else if(a=="--ready-front-off")GTSim::retry_host::ready_front_enabled=false;else if(a=="--retry-memo-off")GTSim::retry_host::enabled=false;else{native_program::need(path.empty()&&a.rfind("--",0)!=0,"unknown option");path=a;}}native_program::need(!path.empty(),"input required");std::ifstream f(path);native_program::need(bool(f),"input open");std::string raw;std::array<char,8192>b{};while(f){f.read(b.data(),b.size());raw.append(b.data(),f.gcount());native_program::need(raw.size()<=2U<<20,"pooled manifest exceeds2MiB");}std::vector<std::set<std::string>> object_keys;auto cb=[&](int,nlohmann::json::parse_event_t e,native_program::J& v){if(e==native_program::J::parse_event_t::object_start)object_keys.emplace_back();if(e==native_program::J::parse_event_t::key)native_program::need(object_keys.back().insert(v.get<std::string>()).second,"duplicate JSON key");if(e==native_program::J::parse_event_t::object_end)object_keys.pop_back();return true;};auto j=native_program::J::parse(raw,cb);auto r=native_sequence::run(j,validate,eager,events);r["input_sha256"]=tiny_sha::sha256(raw);std::cout<<r.dump()<<'\n';return 0;}catch(const std::exception& e){std::cerr<<nlohmann::json({{"status","REJECTED"},{"reason",e.what()}}).dump()<<'\n';return 2;}}
