#pragma once
#include <fstream>
#include "phase_seals.h"
#include "../source_root.h"
namespace attention_bridge {
using namespace prefill_gemm;
struct Profile {std::string name;int grid=8,shared=0,regs=0,resident=0,pcmax=0;std::array<int,4>perwarp{},memcounts{};U nodes=0,read=0,write=0,copies=0,zero=0,tensors=0,ranges=0;};
struct Object {std::string role,logical;U pointer;std::vector<std::pair<U,U>>windows,lines;};
struct Node:prefill_gemm::Node {int memordinal=-1;bool transpose_footprint_only=false,private_tail=false;};
struct Record {int pc;std::string opcode,op;U width,effective,source_mask;std::vector<Global>lanes;};
J read_pin(const J&q,U cap){std::ifstream f(tilegen_source::resolve(q.at("path").get<std::string>()),std::ios::binary);need(bool(f),"pinned plan file");std::string b((std::istreambuf_iterator<char>(f)),std::istreambuf_iterator<char>());need(b.size()==integer(q.at("bytes"),cap)&&tiny_sha::sha256(b)==q.at("sha256").get<std::string>(),"pinned plan SHA/size");return J::parse(b);}
struct Model {
 Profile p;int ctas;U live_nodes=0,live_ranges=0,ranges=0,read=0,write=0,shared_read=0,shared_write=0,copies=0,zero_copies=0,tensors=0,copy_lines=0,read_lines=0,write_lines=0;
 std::vector<Node>nodes;std::vector<Object>objects;std::array<std::array<std::vector<Record>,4>,8>memory;std::vector<g::CtaGraphStore::Span>spans;J profile,entry;
 explicit Model(const J&j){
  need(j.at("schema")=="ATTENTION_STRUCTURAL_RAM_TEMPLATE_V1","closed Attention model schema");std::string phase=j.at("phase");profile=attention_seals().at("phases").at(phase);need(j.at("profile")==profile,"exact phase source contract");p.name=phase;ctas=int(integer(j.at("ctas"),8));need(ctas>0,"finite8 CTA prefix");
  p.nodes=integer(profile.at("nodes"));p.pcmax=int(integer(profile.at("pcmax")));const auto&r=profile.at("native_resources");p.shared=int(add(integer(r.at("static_shared_bytes")),integer(r.at("dynamic_shared_bytes"))));p.regs=int(integer(r.at("registers")));p.resident=int(integer(r.at("max_active_blocks_per_sm"),32));need(p.resident>0&&r.at("threads_per_cta")==128,"actual resource cap");
  for(int w=0;w<4;++w){p.perwarp[w]=int(integer(profile.at("perwarp")[w]));p.memcounts[w]=int(integer(profile.at("memory_counts")[w]));}
  U count=0;for(auto n:p.perwarp)count+=n;need(count==p.nodes,"actual nonuniform warp lengths");
  J plan=read_pin(profile.at("provider").at("plan"),8ULL<<20);need(plan.at("driver_admitted")==false&&plan.at("native_target_qualified")==false,"structural model not old native admission");
  std::string key=j.at("selected_source_key");const J&entries=phase=="Prefill"?plan.at("calls"):plan.at("service_entries");bool found=false;
  for(const auto&e:entries)if(e.at("source_launch_key")==key){need(!found&&(phase=="Prefill"||e.at("phase")==phase),"unique selected phase call");entry=e;found=true;}
  need(found&&entry.at("roles")==j.at("role_windows"),"current canonical call exact role windows");need(entry.at("estimated_control")==true&&entry.at("target_control_equivalence_proven")==false,"explicit estimated target control");
  need(j.at("model_flags")==J({{"estimated_control",true},{"estimated_compute",true},{"estimated_address",true},{"target_control_equivalence_proven",false},{"actual_target_array_values_observed",false},{"actual_array_extents_recovered",false},{"native_target_qualified",false},{"full_LLM_state",false}}),"model uncertainty flags retained");
  need(j.at("scope")==profile.at("scope"),"explicit model authority scope");
  for(const auto&role:profile.at("roles")){const auto&o=entry.at("roles").at(role.get<std::string>());Object v;v.role=role;v.logical=o.at("logical_identity");v.pointer=integer(o.at("argument_pointer"));need(v.pointer&&!v.logical.empty(),"actual argument and logical role");for(const auto&q:o.at("service_byte_intervals")){U lo=integer(q[0]),hi=integer(q[1]);need(lo<hi&&lo>=v.pointer,"bounded minimum request window");v.windows.emplace_back(lo,hi);}for(const auto&q:o.at("cacheline_service_intervals")){U lo=integer(q[0]),hi=integer(q[1]);need(lo<hi&&lo%128==0&&hi%128==0,"128B window cover");v.lines.emplace_back(lo,hi);}need(!v.windows.empty()&&!v.lines.empty(),"used roles only");objects.push_back(std::move(v));}
  auto memraw=j.at("per_cta_memory").dump();need(memraw.size()==integer(profile.at("memory_bytes"))&&tiny_sha::sha256(memraw)==profile.at("memory_sha256").get<std::string>(),"sealed8 CTA address classes");const auto&mt=j.at("per_cta_memory");need(mt.size()==8,"all actual8 CTA address tables");
  for(int c=0;c<8;++c)for(const auto&v:mt[c]){int w=int(integer(v.at("warp"),3)),ordinal=int(integer(v.at("memory_ordinal"),p.memcounts[w]-1));need(ordinal==int(memory[c][w].size()),"actual encounter-order memory ordinal");Record q{int(integer(v.at("pc"),p.pcmax)),v.at("opcode"),v.at("op"),integer(v.at("width"),16),integer(v.at("effective_mask"),UINT32_MAX),integer(v.at("source_read_mask"),UINT32_MAX),{}};need((q.op=="R"||q.op=="W")&&(q.width==4||q.width==8||q.width==16),"ordinary memory form");U mask=0;for(const auto&x:v.at("relative_lanes")){need(x.size()==4,"relative lane tuple");Global z{int(integer(x[0],31)),int(integer(x[1],objects.size()-1)),integer(x[2]),integer(x[3],16)};need(z.width==q.width&&!(mask&(1ULL<<z.lane)),"one exact width per observed lane");mask|=1ULL<<z.lane;const auto&o=objects[z.role];U address=add(o.pointer,z.offset),end=add(address,z.width);bool inside=false;for(auto bounds:o.windows)inside|=bounds.first<=address&&end<=bounds.second;need(inside,"whole target request in minimum observed window");q.lanes.push_back(z);}need(mask==q.source_mask&&(mask&~q.effective)==0,"source-read mask separate from effective copy mask");if(q.opcode.find("LDGSTS")!=0)need(mask==q.effective,"ordinary global effective lanes");memory[c][w].push_back(std::move(q));}
  for(int c=0;c<8;++c)for(int w=0;w<4;++w)need(memory[c][w].size()==U(p.memcounts[w]),"complete actual memory class");
  const auto&ns=j.at("nodes");auto nr=ns.dump();need(ns.is_array()&&ns.size()==p.nodes&&nr.size()==integer(profile.at("node_bytes"))&&tiny_sha::sha256(nr)==profile.at("node_sha256").get<std::string>(),"sealed topologically reordered graph");std::set<int>oldids;std::array<int,4>last{{-1,-1,-1,-1}};std::array<std::set<int>,4>memord;
  const std::set<std::string>kinds={"compute","control","async_copy","async_commit","async_wait","shared_matrix","tensor","barrier","shared","global"};
  for(std::size_t i=0;i<ns.size();++i){const auto&v=ns[i];Node n;n.old=int(integer(v.at("original_id"),p.nodes-1));n.warp=int(integer(v.at("warp"),3));n.ordinal=int(integer(v.at("program_ordinal"),p.perwarp[n.warp]-1));n.pc=int(integer(v.at("pc"),p.pcmax));n.effective=integer(v.at("effective_mask"),UINT32_MAX);n.kind=v.at("kind");n.pipe=v.at("pipeline").is_null()?"":v.at("pipeline").get<std::string>();n.opcode=v.at("opcode");n.elements=int(integer(v.at("elements"),2048));n.width=integer(v.at("width"),16);n.memop=v.at("memory_op").is_null()?"":v.at("memory_op").get<std::string>();
   int base=0;for(int w=0;w<n.warp;++w)base+=p.perwarp[w];need(n.old==base+n.ordinal&&oldids.insert(n.old).second&&n.ordinal>last[n.warp]&&kinds.count(n.kind)&&n.elements>0,"original nonuniform warp identity and issue order");last[n.warp]=n.ordinal;std::set<int>edges;
   for(auto x:v.at("depends_on")){int d=int(integer(x,p.nodes-1));need(d<int(i)&&edges.insert(d).second,"topological completion edge");n.deps.push_back(d);}for(auto x:v.at("issue_depends_on")){int d=int(integer(x,p.nodes-1));need(d<int(i)&&edges.insert(d).second,"topological disjoint issue edge");n.issues.push_back(d);}
   std::set<int>lanes;for(const auto&x:v.at("shared_ranges")){Shared s{int(integer(x[0],31)),integer(x[1],p.shared),integer(x[2],16)};need((s.width==4||s.width==8||s.width==16)&&s.width==n.width&&s.offset%4==0&&add(s.offset,s.width)<=U(p.shared)&&lanes.insert(s.lane).second&&(n.effective>>s.lane&1),"full-width actual shared service footprint");n.shared.push_back(s);}
   if(n.kind=="global"||n.kind=="async_copy"){n.memordinal=int(integer(v.at("memory_record_ordinal"),p.memcounts[n.warp]-1));need(memord[n.warp].insert(n.memordinal).second,"unique memory node");for(int c=0;c<8;++c){const auto&q=memory[c][n.warp][n.memordinal];need(q.pc==n.pc&&q.opcode==n.opcode&&q.width==n.width&&q.effective==n.effective&&q.op==n.memop,"per-CTA actual memory/program join");}}else need(!v.contains("memory_record_ordinal"),"no fabricated memory event");
   if(n.kind=="async_copy"){++copies;n.source_mask=integer(v.at("source_read_mask"),UINT32_MAX);need(n.opcode=="LDGSTS.E.BYPASS.LTC128B.128"&&n.width==16&&n.memop=="R"&&n.shared.size()==U(__builtin_popcount(unsigned(n.effective))),"Attention exact copy opcode/destination");need(integer(v.at("zero_fill_mask"),UINT32_MAX)==(n.effective&~n.source_mask),"retained source-zero model");for(int c=0;c<8;++c)need(memory[c][n.warp][n.memordinal].source_mask==n.source_mask,"all8 observed same copy mask class");zero_copies+=!n.source_mask;for(auto&s:n.shared){need(s.width==16&&s.offset%16==0,"copy destination16B");shared_write+=s.width;}}
   else if(n.kind=="shared"||n.kind=="shared_matrix"){need(!n.shared.empty()&&(n.memop=="R"||n.memop=="W"),"real shared service");if(n.kind=="shared_matrix"){need((n.opcode=="LDSM.16.M88.4"||n.opcode=="LDSM.16.MT88.4")&&n.width==16&&n.memop=="R","qualified source model footprint only");n.transpose_footprint_only=v.at("transpose_footprint_only");need(n.transpose_footprint_only==(n.opcode=="LDSM.16.MT88.4"),"MT88 fragment semantics not invented");}for(auto&s:n.shared)if(n.memop=="R")shared_read+=s.width;else shared_write+=s.width;}
   else need(n.shared.empty(),"no extra shared service");
   if(v.contains("warp_private_after_final_BAR")){need(v.at("warp_private_after_final_BAR")==true&&n.kind=="shared","explicit sealed private tail");n.private_tail=true;}
   if(n.kind=="tensor"){++tensors;n.fma=integer(v.at("declared_fma_work"));need(n.opcode=="HMMA.16816.F32.BF16"&&n.fma==2048,"actual HMMA work");}else if(n.kind=="compute"||n.kind=="control"||n.kind=="async_commit"||n.kind=="async_wait")need(n.pipe=="SIMD"||n.pipe=="SFU"||n.pipe=="SHFL","existing pipeline service");nodes.push_back(std::move(n));
  }
  for(int w=0;w<4;++w)need(last[w]==p.perwarp[w]-1&&memord[w].size()==U(p.memcounts[w]),"all actual perwarp records");
  for(int c=0;c<8;++c){U rd=0,wr=0,rg=0,cl=0,rl=0,wl=0;for(const auto&n:nodes){rg+=n.shared.size();std::set<U>lines;for(auto&x:global(c,n)){rg++;if(n.memop=="R")rd+=x.width;else wr+=x.width;U a=add(objects[x.role].pointer,x.offset);for(U l=a/128;l<=(a+x.width-1)/128;++l)lines.insert(l);}if(n.memop=="R")rl+=lines.size();else wl+=lines.size();if(n.kind=="async_copy")cl+=lines.size();}const auto&q=profile.at("per_CTA")[c];need(rd==integer(q.at("requested_read_bytes"))&&wr==integer(q.at("requested_write_bytes"))&&rg==integer(q.at("all_ranges")),"actual class bytes/ranges");if(c==0){read=rd;write=wr;ranges=rg;copy_lines=cl;read_lines=rl;write_lines=wl;}else need(read==rd&&write==wr&&ranges==rg&&copy_lines==cl&&read_lines==rl&&write_lines==wl,"target byte/transaction class invariance");}
  need(copies==integer(profile.at("kinds").at("async_copy"))&&zero_copies==integer(profile.at("kinds").at("zero_source_copy"))&&tensors==integer(profile.at("kinds").value("tensor",J(0)))&&shared_read==integer(profile.at("shared_read_bytes"))&&shared_write==integer(profile.at("shared_write_bytes")),"source operation and shared work census");p.read=read;p.write=write;p.copies=copies;p.zero=zero_copies;p.tensors=tensors;p.ranges=ranges;live_nodes=U(ctas)*nodes.size();live_ranges=U(ctas)*ranges;need(live_nodes<=100000&&live_ranges<=1000000,"bounded Attention grid host capacity");for(int c=0;c<ctas;++c)spans.push_back({int(c*nodes.size()),int(nodes.size())});
 }
 const std::vector<Global>&global(int c,const Node&n)const{static const std::vector<Global>empty;return n.memordinal<0?empty:memory.at(c).at(n.warp).at(n.memordinal).lanes;}
 J service_map()const{std::vector<std::pair<U,U>>ss;for(const auto&o:objects)for(auto x:o.lines)ss.push_back(x);std::sort(ss.begin(),ss.end());std::vector<std::pair<U,U>>merged;for(auto x:ss){if(!merged.empty()&&x.first<=merged.back().second)merged.back().second=std::max(merged.back().second,x.second);else merged.push_back(x);}J rows=J::array();U off=0;for(auto x:merged){rows.push_back({{"source_base",x.first},{"bytes",x.second-x.first},{"service_base",off}});off+=x.second-x.first;}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};}
};
}
